import { db } from '../db'

export function seedClaims(insurerIds: number[]): number[] {
  const [stateFarmId, allstateId, libertyMutualId] = insurerIds

  const insert = db.prepare(`
    INSERT INTO claims (
      claim_number, insurer_id, claimant_name, claimant_email, claimant_phone,
      property_address, property_type, claim_type, status,
      date_opened, date_closed, estimated_value, final_settlement,
      adjuster_notes, description
    ) VALUES (
      @claim_number, @insurer_id, @claimant_name, @claimant_email, @claimant_phone,
      @property_address, @property_type, @claim_type, @status,
      @date_opened, @date_closed, @estimated_value, @final_settlement,
      @adjuster_notes, @description
    )
  `)

  const claims = [
    {
      claim_number: 'CLM-2024-0001',
      insurer_id: stateFarmId,
      claimant_name: 'John & Mary Harrington',
      claimant_email: 'jharrington@email.com',
      claimant_phone: '(555) 201-3344',
      property_address: '47 Maple St, Springfield IL',
      property_type: 'residential',
      claim_type: 'property_damage',
      status: 'closed',
      date_opened: '2024-01-15',
      date_closed: '2024-03-20',
      estimated_value: 18500,
      final_settlement: 16200,
      adjuster_notes: 'Hail damage confirmed by weather report. Settlement agreed after contractor review.',
      description: 'Claimant reports hail damage to roof and gutters following storm on 2024-01-13. Two shingles missing, flashing bent, interior ceiling stain in master bedroom.',
    },
    {
      claim_number: 'CLM-2024-0002',
      insurer_id: allstateId,
      claimant_name: 'Robert Kim',
      claimant_email: 'rkim@email.com',
      claimant_phone: '(555) 503-9812',
      property_address: '892 Oak Ave, Portland OR',
      property_type: 'residential',
      claim_type: 'fire',
      status: 'submitted',
      date_opened: '2024-02-01',
      date_closed: null,
      estimated_value: 124000,
      final_settlement: null,
      adjuster_notes: 'Fire originated in kitchen. Significant structural damage to rear of property.',
      description: 'Kitchen fire on 2024-01-30 caused by unattended stove. Fire spread to adjacent dining area and rear wall before being extinguished. Smoke damage throughout first floor.',
    },
    {
      claim_number: 'CLM-2024-0003',
      insurer_id: libertyMutualId,
      claimant_name: 'TechCorp LLC',
      claimant_email: 'legal@techcorp.com',
      claimant_phone: '(555) 404-7700',
      property_address: '500 Commerce Blvd, Atlanta GA',
      property_type: 'commercial',
      claim_type: 'liability',
      status: 'disputed',
      date_opened: '2024-02-14',
      date_closed: null,
      estimated_value: 85000,
      final_settlement: null,
      adjuster_notes: '',
      description: 'Slip-and-fall incident in lobby. Claimant alleges inadequate wet floor signage following cleaning. Dispute over liability and extent of injuries.',
    },
    {
      claim_number: 'CLM-2024-0004',
      insurer_id: stateFarmId,
      claimant_name: 'Patricia Walton',
      claimant_email: 'pwalton@email.com',
      claimant_phone: '(555) 504-2281',
      property_address: '33 River Rd, New Orleans LA',
      property_type: 'residential',
      claim_type: 'flood',
      status: 'inspected',
      date_opened: '2024-03-01',
      date_closed: null,
      estimated_value: 42000,
      final_settlement: null,
      adjuster_notes: 'Flood damage consistent with reported rainfall event. Water line confirmed at 18 inches.',
      description: 'Heavy rainfall on 2024-02-27 caused river overflow. Ground floor flooded with approximately 18 inches of water. Flooring, drywall, and electrical outlets affected.',
    },
    {
      claim_number: 'CLM-2024-0005',
      insurer_id: allstateId,
      claimant_name: 'Marcus Johnson',
      claimant_email: 'marcusj@email.com',
      claimant_phone: '(555) 512-6647',
      property_address: '1201 W 5th St, Austin TX',
      property_type: 'residential',
      claim_type: 'theft',
      status: 'report_pending',
      date_opened: '2024-03-15',
      date_closed: null,
      estimated_value: 8900,
      final_settlement: null,
      adjuster_notes: '',
      description: 'Claimant reports break-in on 2024-03-13. Items stolen include electronics, jewelry, and cash. Police report filed (case #APD-2024-03-8812).',
    },
    {
      claim_number: 'CLM-2024-0006',
      insurer_id: libertyMutualId,
      claimant_name: 'Sunrise Cafe',
      claimant_email: 'owner@sunrisecafe.com',
      claimant_phone: '(555) 720-3390',
      property_address: '450 Main St, Denver CO',
      property_type: 'commercial',
      claim_type: 'property_damage',
      status: 'inspection_scheduled',
      date_opened: '2024-04-02',
      date_closed: null,
      estimated_value: 31000,
      final_settlement: null,
      adjuster_notes: '',
      description: 'Pipe burst in ceiling caused water damage to dining area and kitchen. Flooring buckled, ceiling tiles damaged. Business temporarily closed pending repairs.',
    },
    {
      claim_number: 'CLM-2024-0007',
      insurer_id: stateFarmId,
      claimant_name: 'Emma Wilson',
      claimant_email: 'ewilson@email.com',
      claimant_phone: '(555) 206-5513',
      property_address: '78 Birchwood Dr, Seattle WA',
      property_type: 'residential',
      claim_type: 'auto',
      status: 'assigned',
      date_opened: '2024-04-10',
      date_closed: null,
      estimated_value: 12400,
      final_settlement: null,
      adjuster_notes: '',
      description: 'Vehicle struck by fallen tree branch during windstorm on 2024-04-08. Damage to hood, windshield, and roof. Vehicle undriveable.',
    },
    {
      claim_number: 'CLM-2024-0008',
      insurer_id: allstateId,
      claimant_name: 'Carlos Mendez',
      claimant_email: 'cmendez@email.com',
      claimant_phone: '(555) 305-8821',
      property_address: '215 Sunset Blvd, Miami FL',
      property_type: 'residential',
      claim_type: 'property_damage',
      status: 'new',
      date_opened: '2024-04-20',
      date_closed: null,
      estimated_value: 5500,
      final_settlement: null,
      adjuster_notes: '',
      description: 'Fence and shed damaged by neighbor tree fall during thunderstorm. Partial roof damage to shed. Awaiting initial assessment.',
    },
    {
      claim_number: 'CLM-2024-0009',
      insurer_id: libertyMutualId,
      claimant_name: 'Highland Properties',
      claimant_email: 'claims@highlandproperties.com',
      claimant_phone: '(555) 312-4490',
      property_address: '3300 Corporate Dr, Chicago IL',
      property_type: 'commercial',
      claim_type: 'fire',
      status: 'closed',
      date_opened: '2023-11-01',
      date_closed: '2024-01-30',
      estimated_value: 275000,
      final_settlement: 260000,
      adjuster_notes: 'Electrical fire in server room. Cause confirmed by fire marshal report. Full structural assessment completed.',
      description: 'Electrical fire originating in third-floor server room on 2023-10-29. Significant damage to floors 3 and 4. Sprinkler system activated, causing additional water damage on floors 1 and 2.',
    },
    {
      claim_number: 'CLM-2024-0010',
      insurer_id: stateFarmId,
      claimant_name: 'Anna & Tom Fischer',
      claimant_email: 'fischertn@email.com',
      claimant_phone: '(555) 615-7723',
      property_address: '88 Creek Side Ln, Nashville TN',
      property_type: 'residential',
      claim_type: 'flood',
      status: 'new',
      date_opened: '2024-04-25',
      date_closed: null,
      estimated_value: 67000,
      final_settlement: null,
      adjuster_notes: '',
      description: 'Flash flooding on 2024-04-23 caused by heavy rainfall upstream. Ground and first floor extensively flooded. Significant damage to structure, contents, and HVAC system.',
    },
  ]

  const ids: number[] = []
  for (const claim of claims) {
    const result = insert.run(claim)
    ids.push(result.lastInsertRowid as number)
  }

  return ids
}
