import { db } from '../db'

export function seedClaims(insurerIds: number[]): number[] {
  const [fidelidadeId, tranquilidadeId, allianzId] = insurerIds

  const insert = db.prepare(`
    INSERT INTO claims (
      claim_number, insurer_id, claimant_name, claimant_email, claimant_phone,
      property_address, property_type, claim_type, status,
      date_opened, date_closed, estimated_value, final_settlement,
      adjuster_notes, description
    ) VALUES (
      @claim_number, @insurer_id, @claimant_name, @claimant_email, @claimant_phone,
      @property_address, @property_type, @claim_type, @status,
      @date_opened, @date_closed, @estimated_value, @final_settlement,
      @adjuster_notes, @description
    )
  `)

  const claims = [
    // 1 — Danos Materiais / closed (muito antigo — mais de 90 dias)
    {
      claim_number: 'CLM-2023-0001',
      insurer_id: fidelidadeId,
      claimant_name: 'João e Maria Harrington',
      claimant_email: 'joao.harrington@email.pt',
      claimant_phone: '+351 21 201 3344',
      property_address: 'Rua das Acácias, 47, 2900-301 Setúbal',
      property_type: 'residential',
      claim_type: 'property_damage',
      status: 'closed',
      date_opened: '2023-01-15',
      date_closed: '2023-04-20',
      estimated_value: 18500,
      final_settlement: 16200,
      adjuster_notes: 'Danos por granizo confirmados pelo relatório meteorológico do IPMA referente à tempestade de 13 de janeiro de 2023. Acordo de indemnização alcançado após revisão detalhada do orçamento pelo empreiteiro certificado. O custo final ficou abaixo da estimativa inicial devido à substituição parcial em vez de total das caleiras.',
      description: 'O sinistrado reporta danos por granizo no telhado e caleiras na sequência da tempestade de 2023-01-13. Duas fiadas de telhas em falta na vertente norte, remate de chaminé dobrado e mancha de humidade ativa no teto do quarto principal com dimensão de 60×90 cm. Primeira comunicação feita no próprio dia do evento.',
    },
    // 2 — Incêndio / submitted
    {
      claim_number: 'CLM-2023-0002',
      insurer_id: tranquilidadeId,
      claimant_name: 'Roberto Kim',
      claimant_email: 'roberto.kim@email.pt',
      claimant_phone: '+351 21 503 9812',
      property_address: 'Rua do Carvalhal, 892, 4150-201 Porto',
      property_type: 'residential',
      claim_type: 'fire',
      status: 'submitted',
      date_opened: '2023-03-05',
      date_closed: null,
      estimated_value: 124000,
      final_settlement: null,
      adjuster_notes: 'Incêndio com origem confirmada na cozinha — esquecimento do fogão aceso. Danos estruturais significativos na zona traseira do imóvel, incluindo carbonização até ao revestimento da parede exterior. Relatório dos Bombeiros Voluntários do Porto obtido e arquivado. Processo em fase de submissão à seguradora aguarda aprovação final.',
      description: 'Incêndio deflagrou na cozinha em 2023-03-02 devido ao esquecimento do fogão aceso durante a noite. O fogo propagou-se rapidamente à sala de jantar adjacente e à parede traseira antes de ser extinto pelos bombeiros. Danos extensos por fumo em todo o rés-do-chão. Sistema de climatização contaminado com partículas de fumo e fuligem.',
    },
    // 3 — Responsabilidade Civil / disputed (muito antigo)
    {
      claim_number: 'CLM-2023-0003',
      insurer_id: allianzId,
      claimant_name: 'TechLda — Soluções Informáticas',
      claimant_email: 'juridico@techlda.pt',
      claimant_phone: '+351 21 404 7700',
      property_address: 'Av. do Comércio, 500, 4710-301 Braga',
      property_type: 'commercial',
      claim_type: 'liability',
      status: 'disputed',
      date_opened: '2023-04-18',
      date_closed: null,
      estimated_value: 85000,
      final_settlement: null,
      adjuster_notes: 'Queda registada por funcionária visitante no átrio de entrada principal. A empresa alega ausência de sinalização de piso molhado após operação de limpeza matinal. Imagens de videovigilância analisadas — confirmam ausência de sinalética no momento da queda. Processo em litígio: responsabilidade contestada pela empresa de facilities management subcontratada. Aguarda decisão judicial.',
      description: 'Queda por piso escorregadio no átrio de entrada em 2023-04-15. A sinistrada alega que o pavimento estava molhado após lavagem matinal e não havia sinalização de aviso visível. Resultaram fraturas no punho direito e no joelho esquerdo, exigindo cirurgia. Pedido de indemnização inclui despesas médicas, incapacidade temporária e danos morais.',
    },
    // 4 — Inundação / inspected
    {
      claim_number: 'CLM-2023-0004',
      insurer_id: fidelidadeId,
      claimant_name: 'Patrícia Walton',
      claimant_email: 'patricia.walton@email.pt',
      claimant_phone: '+351 21 504 2281',
      property_address: 'Rua do Rio, 33, 3080-810 Figueira da Foz',
      property_type: 'residential',
      claim_type: 'flood',
      status: 'inspected',
      date_opened: '2023-06-10',
      date_closed: null,
      estimated_value: 42000,
      final_settlement: null,
      adjuster_notes: 'Danos por inundação totalmente consistentes com o evento de precipitação extrema reportado pelo IPMA em 2023-06-07. Linha de água confirmada a 45 centímetros de altura em todas as divisões do rés-do-chão. Soalho de madeira massiva irrecuperável. Recomendada remediação de bolores antes do início de qualquer obra de reconstrução. Orçamentos solicitados a três empreiteiros certificados.',
      description: 'Precipitação intensa a montante em 2023-06-07 causou transbordo do rio Mondego. O rés-do-chão ficou inundado com aproximadamente 45 centímetros de água durante cerca de 6 horas. Pavimentos de madeira, paredes em gesso e tomadas elétricas afetados em toda a extensão do piso térreo. Mobiliário e eletrodomésticos destruídos.',
    },
    // 5 — Furto / report_pending (antigo, >90 dias)
    {
      claim_number: 'CLM-2023-0005',
      insurer_id: tranquilidadeId,
      claimant_name: 'Marcos Oliveira',
      claimant_email: 'marcos.oliveira@email.pt',
      claimant_phone: '+351 21 512 6647',
      property_address: 'Rua Cinco de Outubro, 1201, 3000-311 Coimbra',
      property_type: 'residential',
      claim_type: 'theft',
      status: 'report_pending',
      date_opened: '2023-07-20',
      date_closed: null,
      estimated_value: 8900,
      final_settlement: null,
      adjuster_notes: 'Arrombamento confirmado pela PSP. Arrombamento pela janela traseira do rés-do-chão — marcas evidentes no aro e batente. Objetos furtados incluem televisão, computador portátil, câmara fotográfica e joalharia. Participação policial arquivada (PSP-2023-07-8812). Relatório de peritagem em preparação — aguarda avaliação dos objetos recuperados.',
      description: 'O sinistrado reporta arrombamento ocorrido durante a noite de 2023-07-18. Os objetos furtados incluem equipamentos eletrónicos (televisão 65", portátil gaming, câmara DSLR), joalharia avaliada em €3.200 e €400 em numerário. Participação policial apresentada no próprio dia na Esquadra de Coimbra (processo n.º PSP-2023-07-8812).',
    },
    // 6 — Danos Materiais Comercial / inspection_scheduled
    {
      claim_number: 'CLM-2023-0006',
      insurer_id: allianzId,
      claimant_name: 'Café Aurora, Lda.',
      claimant_email: 'gerente@cafeaurora.pt',
      claimant_phone: '+351 21 720 3390',
      property_address: 'Rua Principal, 450, 1100-407 Lisboa',
      property_type: 'commercial',
      claim_type: 'property_damage',
      status: 'inspection_scheduled',
      date_opened: '2023-09-12',
      date_closed: null,
      estimated_value: 31000,
      final_settlement: null,
      adjuster_notes: 'Rebentamento de canalização de abastecimento de água quente no teto falso da sala principal. Danos extensos por água no pavimento de madeira, painéis de teto e equipamento de cozinha. Estabelecimento encerrado desde o evento. Vistoria técnica agendada — aguarda disponibilidade do proprietário do edifício para acesso ao espaço técnico.',
      description: 'Rebentamento de canalização no teto em 2023-09-09 causou inundação por água na sala e na cozinha. Pavimento de madeira empenado e completamente inutilizado em 80% da sala. Painéis de teto falso colapsados em três zonas. Estabelecimento temporariamente encerrado aguardando reparações urgentes e peritagem.',
    },
    // 7 — Auto / assigned
    {
      claim_number: 'CLM-2023-0007',
      insurer_id: fidelidadeId,
      claimant_name: 'Emma Wilson',
      claimant_email: 'emma.wilson@email.pt',
      claimant_phone: '+351 21 206 5513',
      property_address: 'Rua das Bétulas, 78, 2750-310 Cascais',
      property_type: 'residential',
      claim_type: 'auto',
      status: 'assigned',
      date_opened: '2023-10-03',
      date_closed: null,
      estimated_value: 12400,
      final_settlement: null,
      adjuster_notes: 'Viatura sinistrada por queda de ramo de árvore durante temporal. Avaliação de dano total em curso junto da oficina autorizada. Relatório fotográfico recebido — danos visíveis no capô, para-brisas e tejadilho. Processo atribuído ao perito de automóvel. Aguarda orçamento de reparação da oficina parceira.',
      description: 'Viatura BMW Série 3 (matrícula XX-00-XX) atingida por ramo de árvore caído durante tempestade de vento em 2023-09-30. Danos no capô, para-brisas e tejadilho. Veículo imobilizado na via pública — rebocado para oficina autorizada no próprio dia. Sinistrada sem veículo de substituição disponível.',
    },
    // 8 — Danos Materiais / new (recente)
    {
      claim_number: 'CLM-2023-0008',
      insurer_id: tranquilidadeId,
      claimant_name: 'Carlos Mendes',
      claimant_email: 'carlos.mendes@email.pt',
      claimant_phone: '+351 21 305 8821',
      property_address: 'Av. do Pôr do Sol, 215, 8000-401 Faro',
      property_type: 'residential',
      claim_type: 'property_damage',
      status: 'new',
      date_opened: '2023-11-15',
      date_closed: null,
      estimated_value: 5500,
      final_settlement: null,
      adjuster_notes: '',
      description: 'Vedação e arrecadação danificadas pela queda de árvore do prédio vizinho durante trovoada de 2023-11-12. Danos parciais no telhado da arrecadação — três chapas de zinco arrancadas — e dois painéis da vedação amassados. Aguarda contacto inicial e agendamento de vistoria.',
    },
    // 9 — Incêndio Comercial / closed (antigo, encerrado)
    {
      claim_number: 'CLM-2023-0009',
      insurer_id: allianzId,
      claimant_name: 'Propriedades do Norte, S.A.',
      claimant_email: 'sinistros@propriedadesnorte.pt',
      claimant_phone: '+351 22 312 4490',
      property_address: 'Rua Empresarial, 3300, 4470-157 Porto',
      property_type: 'commercial',
      claim_type: 'fire',
      status: 'closed',
      date_opened: '2023-01-05',
      date_closed: '2023-04-30',
      estimated_value: 275000,
      final_settlement: 260000,
      adjuster_notes: 'Incêndio elétrico na sala de servidores confirmado pelo relatório técnico dos Bombeiros Sapadores do Porto. Causa determinada: curto-circuito no quadro de distribuição secundário sem proteção diferencial adequada. Avaliação estrutural completa concluída por engenheiro de estruturas certificado. Acordo de indemnização final negociado após revisão detalhada dos orçamentos e deprevisão.',
      description: 'Incêndio elétrico com origem na sala de servidores do terceiro piso em 2023-01-02. Danos estruturais e de conteúdos significativos nos pisos 3 e 4. Ativação automática do sistema de sprinklers causou danos adicionais por água nos pisos 1 e 2. Edifício parcialmente evacuado durante 48 horas.',
    },
    // 10 — Inundação / new (antigo, >90 dias)
    {
      claim_number: 'CLM-2023-0010',
      insurer_id: fidelidadeId,
      claimant_name: 'Ana e Tomás Fischer',
      claimant_email: 'fischertn@email.pt',
      claimant_phone: '+351 21 615 7723',
      property_address: 'Rua da Ribeira, 88, 3810-101 Aveiro',
      property_type: 'residential',
      claim_type: 'flood',
      status: 'new',
      date_opened: '2023-02-01',
      date_closed: null,
      estimated_value: 67000,
      final_settlement: null,
      adjuster_notes: '',
      description: 'Cheia repentina em 2023-01-29 causada por precipitação intensa e colapso parcial de galeria pluvial a montante. Rés-do-chão e primeiro piso inundados — nível de água estimado em 80 cm no piso térreo. Danos significativos na estrutura, conteúdos e sistema de climatização. Família realojada em alojamento temporário.',
    },
    // 11 — Responsabilidade Civil / closed (2023, encerrado)
    {
      claim_number: 'CLM-2023-0011',
      insurer_id: tranquilidadeId,
      claimant_name: 'Supermercado Bom Preço, Lda.',
      claimant_email: 'geral@superbompreco.pt',
      claimant_phone: '+351 21 830 4420',
      property_address: 'Rua do Mercado, 12, 2400-201 Leiria',
      property_type: 'commercial',
      claim_type: 'liability',
      status: 'closed',
      date_opened: '2023-05-10',
      date_closed: '2023-09-14',
      estimated_value: 22000,
      final_settlement: 19500,
      adjuster_notes: 'Sinistrado (cliente) sofreu queda ao escorregar em produto derramado no corredor de laticínios. Câmeras de vigilância confirmaram ausência de sinalética de aviso durante o período crítico. Responsabilidade do estabelecimento confirmada. Acordo extrajudicial alcançado antes do prazo judicial. Indemnização inclui despesas médicas e incapacidade temporária parcial.',
      description: 'Cliente sofreu queda no interior do supermercado em 2023-05-08, ao escorregar em iogurte derramado no corredor. Resultaram contusões no ombro direito e entorse do tornozelo. Baixa médica de 3 semanas. Processo resolvido por acordo extrajudicial.',
    },
    // 12 — Furto Comercial / submitted
    {
      claim_number: 'CLM-2024-0012',
      insurer_id: allianzId,
      claimant_name: 'Joalharia Prata Fina, Lda.',
      claimant_email: 'gerencia@pratafina.pt',
      claimant_phone: '+351 22 441 9900',
      property_address: 'Rua de Santa Catarina, 78, 4000-447 Porto',
      property_type: 'commercial',
      claim_type: 'theft',
      status: 'submitted',
      date_opened: '2024-01-08',
      date_closed: null,
      estimated_value: 186000,
      final_settlement: null,
      adjuster_notes: 'Assalto à mão armada ocorrido durante horário de funcionamento. Dois funcionários presentes foram imobilizados. PSP e PJ acionadas no próprio dia. Relatório de inventário detalhado dos artigos furtados fornecido pelo seguro de conteúdos. Peças de alto valor incluem anéis em ouro e diamantes, colares e relógios de marca. Processo em fase de submissão à seguradora.',
      description: 'Assalto à mão armada na joalharia em 2024-01-05, durante horário de funcionamento (15h20). Dois indivíduos encapuzados imobilizaram dois funcionários e furtaram o conteúdo das montras e do cofre. PJ assume investigação. Inventário de peças furtadas avaliadas em €186.000, incluindo peças únicas de coleção.',
    },
    // 13 — Inundação Comercial / inspected
    {
      claim_number: 'CLM-2024-0013',
      insurer_id: fidelidadeId,
      claimant_name: 'Hotel Bela Vista, S.A.',
      claimant_email: 'manutencao@hotelbelavista.pt',
      claimant_phone: '+351 289 501 234',
      property_address: 'Av. Infante D. Henrique, 22, 8200-412 Albufeira',
      property_type: 'commercial',
      claim_type: 'flood',
      status: 'inspected',
      date_opened: '2024-02-20',
      date_closed: null,
      estimated_value: 98000,
      final_settlement: null,
      adjuster_notes: 'Inundação de origem interna: rutura de tubagem de abastecimento de água no piso 4 durante a madrugada. Água infiltrou-se pelos pisos 4, 3 e 2 ao longo de cerca de 4 horas antes de ser detetada. Quartos afetados: 401 a 412, 301 a 308 e 201 a 204. Relatório de inspeção com mapeamento de danos completo arquivado. Orçamentos recebidos de dois empreiteiros hoteleiros especializados.',
      description: 'Rutura de tubagem de abastecimento de água quente no corredor do piso 4 do hotel em 2024-02-17, pelas 03h30. Infiltração de água danificou tetos, paredes, alcatifas e mobiliário de 26 quartos em três pisos. Hotel operou com capacidade reduzida de 40% durante duas semanas.',
    },
    // 14 — Auto / report_pending
    {
      claim_number: 'CLM-2024-0014',
      insurer_id: tranquilidadeId,
      claimant_name: 'Luísa Monteiro',
      claimant_email: 'luisa.monteiro@email.pt',
      claimant_phone: '+351 21 930 5577',
      property_address: 'Rua da Paz, 9, 2805-102 Almada',
      property_type: 'residential',
      claim_type: 'auto',
      status: 'report_pending',
      date_opened: '2024-03-14',
      date_closed: null,
      estimated_value: 28500,
      final_settlement: null,
      adjuster_notes: 'Colisão traseira na A2 causou danos severos na zona traseira do veículo. Airbags traseiros ativados. Veículo rebocado para oficina autorizada. Sinistrada queixa-se de dores cervicais — consulta com traumatologista em curso. Relatório médico e orçamento de reparação da oficina aguardados para conclusão do processo.',
      description: 'Colisão traseira na A2 (sentido Sul-Norte, km 14) em 2024-03-11, às 18h45, em pleno tráfego de regresso. Veículo Volkswagen Golf (matrícula YY-11-YY) embateu na traseira do carro da sinistrada (Renault Clio, ZZ-22-ZZ) a velocidade elevada. Danos graves na traseira. Sinistrada queixa-se de dores cervicais e lombares.',
    },
    // 15 — Incêndio Residencial / new (recente)
    {
      claim_number: 'CLM-2024-0015',
      insurer_id: allianzId,
      claimant_name: 'Fernando e Conceição Brito',
      claimant_email: 'fcbrito@email.pt',
      claimant_phone: '+351 21 720 8843',
      property_address: 'Travessa das Amendoeiras, 5, 2710-413 Sintra',
      property_type: 'residential',
      claim_type: 'fire',
      status: 'new',
      date_opened: '2024-04-05',
      date_closed: null,
      estimated_value: 55000,
      final_settlement: null,
      adjuster_notes: '',
      description: 'Incêndio de pequena dimensão em 2024-04-03, com origem na cave, propagou-se à garagem e à entrada da habitação. Causa provável: curto-circuito no painel de distribuição elétrica. Bombeiros de Sintra controlaram o fogo em 45 minutos. Danos na estrutura da cave, garagem e entrada, além de perda de veículo e conteúdos.',
    },
    // 16 — Outros / inspection_scheduled
    {
      claim_number: 'CLM-2024-0016',
      insurer_id: fidelidadeId,
      claimant_name: 'Clínica Dentária Sorrisão, Lda.',
      claimant_email: 'admin@clinicasorriso.pt',
      claimant_phone: '+351 21 358 7711',
      property_address: 'Rua Dr. António José de Almeida, 101, 1000-043 Lisboa',
      property_type: 'commercial',
      claim_type: 'other',
      status: 'inspection_scheduled',
      date_opened: '2024-04-22',
      date_closed: null,
      estimated_value: 14000,
      final_settlement: null,
      adjuster_notes: 'Danos causados por vibração de obras de construção no edifício adjacente. Fissuras em paredes interiores e no piso de porcelana de alta precisão da sala de tratamentos. Equipamento odontológico pode ter sido afetado por vibrações — avaliação técnica especializada necessária. Vistoria agendada com perito de estruturas.',
      description: 'Obras de demolição e construção no edifício adjacente durante fevereiro e março de 2024 causaram vibrações que danificaram as instalações da clínica. Fissuras progressivas em paredes e pavimento, desalinhamento de portas e janelas. Equipamento de imagiologia dentária apresenta erros de calibração após o período das obras.',
    },
    // 17 — Danos Materiais / assigned
    {
      claim_number: 'CLM-2024-0017',
      insurer_id: tranquilidadeId,
      claimant_name: 'Rui e Filomena Gomes',
      claimant_email: 'rui.gomes@email.pt',
      claimant_phone: '+351 21 441 2293',
      property_address: 'Rua das Amendoeiras, 15, 2890-205 Alcochete',
      property_type: 'residential',
      claim_type: 'property_damage',
      status: 'assigned',
      date_opened: '2024-05-03',
      date_closed: null,
      estimated_value: 9800,
      final_settlement: null,
      adjuster_notes: 'Danos por queda de granizo e vento forte — evento confirmado pelo IPMA para a margem sul do Tejo em 2 de maio de 2024. Telhado em telha marselha danificado em aproximadamente 30% da área total. Caleiras e rufos torcidos. Janela do sótão partida. Processo atribuído — vistoria a agendar.',
      description: 'Tempestade de granizo e vento forte em 2024-05-02 causou danos no telhado, caleiras e janela do sótão. Telhas partidas ou deslocadas em várias zonas do telhado. Caleiras de zinco deformadas na fachada principal e lateral. Janela de mansarda com vidro duplo completamente partido.',
    },
    // 18 — Furto Residencial / closed
    {
      claim_number: 'CLM-2024-0018',
      insurer_id: allianzId,
      claimant_name: 'Beatriz Carvalho',
      claimant_email: 'beatriz.carvalho@email.pt',
      claimant_phone: '+351 21 612 5509',
      property_address: 'Av. de Ceuta, 77, 2710-561 Sintra',
      property_type: 'residential',
      claim_type: 'theft',
      status: 'closed',
      date_opened: '2024-01-22',
      date_closed: '2024-04-10',
      estimated_value: 6200,
      final_settlement: 5400,
      adjuster_notes: 'Arrombamento confirmado pela GNR de Sintra. Entrada forçada pela janela lateral. Objetos furtados identificados e parcialmente recuperados pela GNR numa operação posterior. Indemnização calculada com base nos artigos não recuperados e aplicação de cláusula de primeiro risco. Processo encerrado com acordo.',
      description: 'Arrombamento em 2024-01-19 durante ausência da residente por viagem. Entrada forçada pela janela do quarto lateral. Furtados: portátil, tablet, câmara fotográfica, joalharia e relógio de coleção. Participação na GNR no próprio dia de regresso (2024-01-21). GNR recuperou parte dos objetos numa operação 15 dias depois.',
    },
    // 19 — Inundação / submitted (2024)
    {
      claim_number: 'CLM-2024-0019',
      insurer_id: fidelidadeId,
      claimant_name: 'Armazém Geral Lisboa, S.A.',
      claimant_email: 'operacoes@armazem-geral.pt',
      claimant_phone: '+351 21 155 9900',
      property_address: 'Zona Industrial de Sacavém, Lote 14, 2685-339 Sacavém',
      property_type: 'commercial',
      claim_type: 'flood',
      status: 'submitted',
      date_opened: '2024-03-28',
      date_closed: null,
      estimated_value: 320000,
      final_settlement: null,
      adjuster_notes: 'Inundação de grande escala do armazém industrial após rotura de dique de proteção do Rio Trancão em 2024-03-25. Toda a área de armazenagem do piso térreo afetada com nível de água entre 120 e 180 cm. Stock significativo destruído. Infraestrutura elétrica, maquinaria de movimentação e sistema de frio completamente inutilizados. Processo submetido com relatório técnico completo.',
      description: 'Rotura de dique de proteção na margem do Rio Trancão em 2024-03-25, às 06h00, inundou toda a zona industrial baixa de Sacavém. O armazém (área de 4.800 m²) ficou submerso entre 120 e 180 cm durante cerca de 18 horas. Stock de mercadoria avaliado em €180.000 destruído. Instalações elétricas, equipamento de frio e frota de empilhadores inutilizados.',
    },
    // 20 — Responsabilidade Civil / new (recente)
    {
      claim_number: 'CLM-2025-0020',
      insurer_id: tranquilidadeId,
      claimant_name: 'Construtora Minho & Douro, Lda.',
      claimant_email: 'geral@minhodouro.pt',
      claimant_phone: '+351 22 550 1122',
      property_address: 'Rua da Indústria, 88, 4480-112 Vila do Conde',
      property_type: 'commercial',
      claim_type: 'liability',
      status: 'new',
      date_opened: '2025-06-01',
      date_closed: null,
      estimated_value: 47000,
      final_settlement: null,
      adjuster_notes: '',
      description: 'Operário de subempreiteiro sofreu queda de andaime no estaleiro de obra em 2025-05-28. Fratura do úmero e costelas partidas. Operário hospitalizado. Inspeção do Trabalho (ACT) notificada. Processo de responsabilidade civil contra a construtora geral em curso. Aguarda constituição de advogado e início de peritagem das condições de segurança do estaleiro.',
    },
  ]

  const ids: number[] = []
  for (const claim of claims) {
    const result = insert.run(claim)
    ids.push(result.lastInsertRowid as number)
  }

  return ids
}
