import { db } from '../db'

export function seedClaims(insurerIds: number[]): { claimIds: number[]; claimNumbers: string[] } {
  const [fidelidadeId, tranquilidadeId, allianzId] = insurerIds

  const insert = db.prepare(`
    INSERT INTO claims (
      claim_number, insurer_id, claimant_name, claimant_email, claimant_phone,
      property_address, property_type, claim_type, status,
      date_opened, date_closed, estimated_value, final_settlement,
      adjuster_notes, description
    ) VALUES (
      @claim_number, @insurer_id, @claimant_name, @claimant_email, @claimant_phone,
      @property_address, @property_type, @claim_type, @status,
      @date_opened, @date_closed, @estimated_value, @final_settlement,
      @adjuster_notes, @description
    )
  `)

  const claims = [
    // 1 — Danos Materiais / closed — Fidelidade
    {
      claim_number: 'CLM-2025-0001',
      insurer_id: fidelidadeId,
      claimant_name: 'Paulo e Helena Rodrigues',
      claimant_email: 'paulo.hrodrigues@gmail.com',
      claimant_phone: '+351 912 111 222',
      property_address: 'Rua das Flores, 34, 2900-443 Setúbal',
      property_type: 'residential',
      claim_type: 'property_damage',
      status: 'closed',
      date_opened: '2025-09-05',
      date_closed: '2025-12-10',
      estimated_value: 14800,
      final_settlement: 13200,
      adjuster_notes: 'Danos causados por tempestade de vento forte confirmados pelo relatório meteorológico do IPMA para o evento de 2 de setembro de 2025. Queda de árvore do prédio vizinho sobre o telhado e vedação. Acordo alcançado após revisão dos dois orçamentos recebidos. Empreiteiro certificado executou os trabalhos em novembro. Dossier completo arquivado.',
      description: 'Durante a tempestade do dia 2 de setembro de 2025, uma árvore de grande porte no lote adjacente tombou sobre o telhado da habitação e destruiu parte da vedação de alvenaria. Danos visíveis: três fiadas de telha cerâmica arrancadas na vertente sul, deformação do frechal de madeira e mancha de humidade activa no teto do quarto de casal. Vedação danificada em cerca de 8 metros lineares.',
    },
    // 2 — Incêndio / closed — Tranquilidade
    {
      claim_number: 'CLM-2025-0002',
      insurer_id: tranquilidadeId,
      claimant_name: 'Loja de Decoração Alma, Lda.',
      claimant_email: 'geral@lojaalma.pt',
      claimant_phone: '+351 21 345 6789',
      property_address: 'Rua Augusta, 210, 1100-055 Lisboa',
      property_type: 'commercial',
      claim_type: 'fire',
      status: 'closed',
      date_opened: '2025-09-12',
      date_closed: '2026-01-20',
      estimated_value: 92000,
      final_settlement: 87500,
      adjuster_notes: 'Incêndio originado em instalação eléctrica defeituosa na arrecadação traseira, confirmado pelo relatório técnico dos Bombeiros de Lisboa. Danos extensos por fogo e fumo no armazém e parte da área de venda. Peritagem de conteúdos realizada por perita especializada. Processo encerrado após aprovação final da Tranquilidade e pagamento da indemnização em janeiro de 2026.',
      description: 'Incêndio deflagrou na madrugada do dia 10 de setembro de 2025 na arrecadação traseira da loja, por curto-circuito na instalação eléctrica do quadro de distribuição. O fogo propagou-se ao armazém e à zona de exposição de produtos. Sistema de sprinklers activou e controlou parcialmente o incêndio, mas causou danos adicionais por água no stock não atingido pelas chamas.',
    },
    // 3 — Responsabilidade Civil / closed — Allianz
    {
      claim_number: 'CLM-2025-0003',
      insurer_id: allianzId,
      claimant_name: 'Ginásio FitLife, Lda.',
      claimant_email: 'juridico@fitlife.pt',
      claimant_phone: '+351 21 887 3300',
      property_address: 'Av. de Roma, 45, 1700-340 Lisboa',
      property_type: 'commercial',
      claim_type: 'liability',
      status: 'closed',
      date_opened: '2025-09-20',
      date_closed: '2026-02-14',
      estimated_value: 28000,
      final_settlement: 24500,
      adjuster_notes: 'Utente sofreu queda na zona de piscina por piso molhado sem sinalização adequada. Câmeras de videovigilância confirmaram ausência de sinalização no momento do acidente. Relatório médico documentou entorse grave do tornozelo com necessidade de imobilização durante 6 semanas. Acordo extrajudicial alcançado em fevereiro de 2026 após negociação com advogado da lesada.',
      description: 'Em 18 de setembro de 2025, uma utente do ginásio sofreu queda na zona de passagem entre os balneários e a piscina coberta, ao escorregar em pavimento molhado. Não havia sinalização de aviso visível. Resultaram entorse grave do tornozelo direito com fractura associada, exigindo imobilização ortopédica e fisioterapia de recuperação durante 8 semanas. Baixa laboral de 6 semanas declarada.',
    },
    // 4 — Auto / assigned — Fidelidade
    {
      claim_number: 'CLM-2025-0004',
      insurer_id: fidelidadeId,
      claimant_name: 'Tiago Ferreira Alves',
      claimant_email: 'tiago.alves@outlook.pt',
      claimant_phone: '+351 934 567 001',
      property_address: 'Rua Cidade de Viseu, 12, 2750-329 Cascais',
      property_type: 'residential',
      claim_type: 'auto',
      status: 'assigned',
      date_opened: '2025-10-03',
      date_closed: null,
      estimated_value: 18600,
      final_settlement: null,
      adjuster_notes: 'Colisão lateral com veículo que invadiu a faixa de rodagem na EN6 em Cascais. Danos extensos na lateral direita do veículo, incluindo dois painéis de porta amassados, jante traseira direita e pneu destruídos e espelho retrovisor partido. Processo atribuído a perito automóvel. Aguarda orçamento da oficina autorizada Toyota parceira.',
      description: 'Em 1 de outubro de 2025, o sinistrado circulava na EN6 em direção a Lisboa quando um veículo Toyota Yaris (matrícula AA-11-BB) invadiu a faixa da esquerda e embateu lateralmente no seu carro Toyota Corolla (CC-22-DD). O Boletim de Acidente Amigável foi preenchido no local. Danos visíveis na porta dianteira direita, porta traseira direita, jante e pneu traseiro direito e retrovisor.',
    },
    // 5 — Inundação / assigned — Tranquilidade
    {
      claim_number: 'CLM-2025-0005',
      insurer_id: tranquilidadeId,
      claimant_name: 'Cristina e Manuel Saraiva',
      claimant_email: 'cmsaraiva@sapo.pt',
      claimant_phone: '+351 21 512 4433',
      property_address: 'Beco da Ribeira, 7, 3080-820 Figueira da Foz',
      property_type: 'residential',
      claim_type: 'flood',
      status: 'assigned',
      date_opened: '2025-10-18',
      date_closed: null,
      estimated_value: 38500,
      final_settlement: null,
      adjuster_notes: 'Inundação por precipitação extrema confirmada pelo IPMA para o evento de 14 e 15 de outubro de 2025 na região de Coimbra/Figueira da Foz. Rés-do-chão da habitação afectado com nível de água estimado em 35 cm. Pavimento de mosaico e paredes de gesso afectados. Processo atribuído ao perito de inundações. Vistoria a agendar com urgência.',
      description: 'As chuvas intensas dos dias 14 e 15 de outubro de 2025 provocaram o transbordo da Vala de Quiaios, inundando a zona baixa onde se situa a habitação. O rés-do-chão foi inundado com cerca de 35 cm de água durante aproximadamente 4 horas. Afectados: pavimento de mosaico, rodapés, paredes de reboco e tecto falso da sala, cozinha e hall de entrada. Tomadas eléctricas abaixo da linha de água.',
    },
    // 6 — Furto / inspection_scheduled — Allianz
    {
      claim_number: 'CLM-2025-0006',
      insurer_id: allianzId,
      claimant_name: 'Ourivesaria Dourada, Lda.',
      claimant_email: 'gerencia@ourivesariadourada.pt',
      claimant_phone: '+351 22 339 4420',
      property_address: 'Rua de Santa Catarina, 101, 4000-451 Porto',
      property_type: 'commercial',
      claim_type: 'theft',
      status: 'inspection_scheduled',
      date_opened: '2025-11-03',
      date_closed: null,
      estimated_value: 145000,
      final_settlement: null,
      adjuster_notes: 'Assalto com arrombamento nocturno ao estabelecimento de ourivesaria. Arrombamento pela porta traseira de serviço. Cofre-forte perfurado com equipamento especializado. PJ e PSP notificadas no próprio dia. Inventário parcial de artigos furtados em preparação. Perito de joalharia agendado para vistoria ao local e avaliação do stock em falta.',
      description: 'Na madrugada de 1 de novembro de 2025, desconhecidos arrombaram a porta traseira da ourivesaria e perfuraram o cofre com rebarbadora. Foram furtados anéis, colares, brincos e relógios avaliados em cerca de €120.000, além de €25.000 em numerário do fundo de reserva. Sistema de alarme foi neutralizado antes da intrusão. Câmeras de videovigilância externas captaram dois indivíduos encapuzados.',
    },
    // 7 — Danos Materiais / inspection_scheduled — Fidelidade
    {
      claim_number: 'CLM-2025-0007',
      insurer_id: fidelidadeId,
      claimant_name: 'Hotel Quinta do Lago, S.A.',
      claimant_email: 'sinistros@quintadolago-hotel.pt',
      claimant_phone: '+351 289 441 200',
      property_address: 'Quinta do Lago, Almancil, 8135-024 Loulé',
      property_type: 'commercial',
      claim_type: 'property_damage',
      status: 'inspection_scheduled',
      date_opened: '2025-11-15',
      date_closed: null,
      estimated_value: 67000,
      final_settlement: null,
      adjuster_notes: 'Danos por granizo e vento forte na cobertura das piscinas e telhado do spa durante tempestade de 12 de novembro de 2025. Cobertura de policarbonato da piscina exterior destruída em 60% da área. Claraboias do spa com vidros partidos. Vistoria técnica agendada para semana de 25 de novembro com perito de estruturas e especialista em coberturas comerciais.',
      description: 'A tempestade de 12 de novembro de 2025 com granizo de grande calibre e rajadas de vento de mais de 100 km/h destruiu a cobertura de policarbonato translúcido da piscina exterior do hotel (área de 280 m²). Quatro claraboias no tecto do spa ficaram com vidros partidos. Danos menores em caleiras e rufos do edifício principal. Estabelecimento manteve a actividade mas as instalações afectadas foram encerradas temporariamente.',
    },
    // 8 — Incêndio / inspected — Tranquilidade
    {
      claim_number: 'CLM-2025-0008',
      insurer_id: tranquilidadeId,
      claimant_name: 'António e Rosa Marques',
      claimant_email: 'arosam@hotmail.pt',
      claimant_phone: '+351 963 112 233',
      property_address: 'Travessa do Outeiro, 22, 4710-400 Braga',
      property_type: 'residential',
      claim_type: 'fire',
      status: 'inspected',
      date_opened: '2025-11-28',
      date_closed: null,
      estimated_value: 48000,
      final_settlement: null,
      adjuster_notes: 'Incêndio de origem elétrica na garagem propagou-se ao arrumos e à parte inferior da escada de acesso ao piso superior. Vistoria realizada em 5 de dezembro por perita de incêndios. Causa confirmada: sobrecarga na extensão eléctrica do posto de carregamento de veículo eléctrico caseiro não homologado. Danos estruturais na parede de separação garagem/corredor. Processo em fase de avaliação de orçamentos.',
      description: 'Na tarde de 26 de novembro de 2025, deflagrou um incêndio na garagem da habitação por sobrecarga no carregador caseiro do veículo eléctrico. O fogo destruiu o automóvel estacionado, o arrumos contíguo e danificou gravemente a parede de separação entre a garagem e o hall de entrada. Danos por fumo foram detectados no corredor e na sala adjacente ao hall. Bombeiros de Braga controlaram o incêndio em 30 minutos.',
    },
    // 9 — Responsabilidade Civil / inspected — Allianz
    {
      claim_number: 'CLM-2025-0009',
      insurer_id: allianzId,
      claimant_name: 'Supermercado Frescos & Co., Lda.',
      claimant_email: 'juridico@frescosco.pt',
      claimant_phone: '+351 21 455 9900',
      property_address: 'Rua do Centro Comercial, 33, 2745-212 Queluz',
      property_type: 'commercial',
      claim_type: 'liability',
      status: 'inspected',
      date_opened: '2025-12-02',
      date_closed: null,
      estimated_value: 19500,
      final_settlement: null,
      adjuster_notes: 'Queda de cliente idoso na entrada do supermercado por desnível não sinalizado entre o passeio e o pavimento da loja. Câmeras de vigilância e relatório do responsável de turno obtidos. Perito avaliou o local e identificou desnível de 4 cm sem qualquer sinalização ou rampa de acesso conforme a lei. Responsabilidade do estabelecimento confirmada. Processo em avaliação do valor da indemnização.',
      description: 'Em 30 de novembro de 2025, um cliente de 72 anos tropeçou num desnível não sinalizado de 4 cm entre o passeio e o pavimento interior do supermercado, na entrada principal. Resultaram uma fractura do rádio do pulso esquerdo e contusões no ombro. O cliente foi transportado de urgência para o Hospital Fernando da Fonseca. Relatório médico confirma 4 semanas de imobilização e fisioterapia.',
    },
    // 10 — Inundação / inspected — Fidelidade
    {
      claim_number: 'CLM-2025-0010',
      insurer_id: fidelidadeId,
      claimant_name: 'Armazém Logístico Central, S.A.',
      claimant_email: 'sinistros@alcentral.pt',
      claimant_phone: '+351 21 955 3300',
      property_address: 'Zona Industrial Norte, Lote 8, 3800-533 Aveiro',
      property_type: 'commercial',
      claim_type: 'flood',
      status: 'inspected',
      date_opened: '2025-12-10',
      date_closed: null,
      estimated_value: 215000,
      final_settlement: null,
      adjuster_notes: 'Inundação industrial de grande escala durante o episódio de precipitação extrema de 7 e 8 de dezembro de 2025 na região de Aveiro. Armazém submerso com nível de água de 80 cm durante 12 horas. Stock e equipamento industriais com danos significativos. Vistoria técnica completa realizada a 15 de dezembro. Relatório em preparação. Processo complexo com múltiplas categorias de dano.',
      description: 'As chuvas excepcionais de 7 e 8 de dezembro de 2025 provocaram o transbordo do Canal de São Roque, inundando toda a zona industrial norte de Aveiro. O armazém (3.200 m²) ficou com 80 cm de água durante cerca de 12 horas. Afectados: stock paletizado em 70% das localizações, sistema eléctrico completo, duas linhas de paletização automática e um empilhador eléctrico. Escritórios no piso térreo completamente destruídos.',
    },
    // 11 — Auto / report_pending — Tranquilidade
    {
      claim_number: 'CLM-2025-0011',
      insurer_id: tranquilidadeId,
      claimant_name: 'Marta Gonçalves Pinto',
      claimant_email: 'marta.pinto@gmail.com',
      claimant_phone: '+351 916 788 900',
      property_address: 'Av. Almirante Gago Coutinho, 83, 1700-027 Lisboa',
      property_type: 'residential',
      claim_type: 'auto',
      status: 'report_pending',
      date_opened: '2025-12-18',
      date_closed: null,
      estimated_value: 31200,
      final_settlement: null,
      adjuster_notes: 'Colisão frontal com ângulo de 45° na Pontinha durante hora de ponta. Airbags dianteiros activados. Danos graves no capô, para-choques e estrutura frontal. Veículo rebocado para oficina autorizada Peugeot. Sinistrada com queixas de dores no pescoço e costas — consulta com ortopedista a aguardar. Relatório médico e orçamento da oficina pendentes para conclusão do processo.',
      description: 'Em 16 de dezembro de 2025, às 08h30, na Rua da Pontinha em Lisboa, o veículo da sinistrada (Peugeot 308, EE-33-FF) foi embatido de frente com ângulo por um Seat Ibiza (GG-44-HH) que avançou sinal vermelho. Ambos os airbags dianteiros do Peugeot activaram. Danos graves na frente do veículo incluindo capô empenado, para-choques destruído e possível dano na longarina. Sinistrada com dores cervicais e lombares.',
    },
    // 12 — Furto / report_pending — Allianz
    {
      claim_number: 'CLM-2026-0012',
      insurer_id: allianzId,
      claimant_name: 'Bruno e Filipa Castanheira',
      claimant_email: 'brunofcastanheira@sapo.pt',
      claimant_phone: '+351 961 234 567',
      property_address: 'Rua das Camélias, 9, 2710-561 Sintra',
      property_type: 'residential',
      claim_type: 'theft',
      status: 'report_pending',
      date_opened: '2026-01-07',
      date_closed: null,
      estimated_value: 11400,
      final_settlement: null,
      adjuster_notes: 'Arrombamento por janela lateral durante ausência prolongada dos residentes nas férias de Natal. Entrada forçada confirmada pela GNR de Sintra — marcas de arrombamento na caixilharia. Furtados: portátil de trabalho, câmara fotográfica, joalharia de família e numerário. Relatório de peritagem de conteúdos em preparação — aguarda confirmação dos valores das peças de joalharia com avaliador independente.',
      description: 'Em data não precisamente determinada durante as férias de Natal (entre 22 de dezembro de 2025 e 3 de janeiro de 2026), foram furtados bens do interior da habitação por arrombamento da janela lateral da cozinha. Furtados: portátil Dell (trabalho), câmara Sony mirrorless com duas objetivas, joalharia avaliada em €4.500 e €800 em numerário. Participação apresentada na GNR de Sintra a 3 de janeiro de 2026.',
    },
    // 13 — Danos Materiais / submitted — Fidelidade
    {
      claim_number: 'CLM-2026-0013',
      insurer_id: fidelidadeId,
      claimant_name: 'Clínica Médica São Lucas, Lda.',
      claimant_email: 'sinistros@clinicasaolucas.pt',
      claimant_phone: '+351 21 357 8800',
      property_address: 'Rua Marquês de Sá da Bandeira, 20, 1050-149 Lisboa',
      property_type: 'commercial',
      claim_type: 'property_damage',
      status: 'submitted',
      date_opened: '2026-01-13',
      date_closed: null,
      estimated_value: 54000,
      final_settlement: null,
      adjuster_notes: 'Rebentamento de canalização de abastecimento no tecto falso do segundo andar durante o fim-de-semana de 10-11 de janeiro. Água inundou o consultório de dermatologia e o laboratório de análises no piso 2, e provocou infiltrações no corredor e sala de espera do piso 1. Processo submetido à Fidelidade com relatório técnico, orçamentos e relatório de peritagem. Aguarda aprovação da seguradora.',
      description: 'Durante o fim-de-semana prolongado de 10-11 de janeiro de 2026, a rebentamento de uma tubagem de AVAC no tecto falso do segundo andar libertou água durante cerca de 16 horas. O consultório de dermatologia e o laboratório de análises ficaram completamente inundados. Equipamento médico e de laboratório danificados ou destruídos. Danos por infiltração no corredor, sala de espera e recepção do piso inferior.',
    },
    // 14 — Incêndio / submitted — Tranquilidade
    {
      claim_number: 'CLM-2026-0014',
      insurer_id: tranquilidadeId,
      claimant_name: 'João Nuno Figueiredo',
      claimant_email: 'jnfigueiredo@hotmail.pt',
      claimant_phone: '+351 935 678 901',
      property_address: 'Rua de São Mamede, 15, 4000-501 Porto',
      property_type: 'residential',
      claim_type: 'fire',
      status: 'submitted',
      date_opened: '2026-01-25',
      date_closed: null,
      estimated_value: 76000,
      final_settlement: null,
      adjuster_notes: 'Incêndio que destruiu parcialmente a cozinha e a sala de jantar de apartamento no Porto. Origem confirmada pelos Bombeiros Sapadores do Porto: vela acesa esquecida próximo de cortinado. Danos graves por fogo e fumo na cozinha, sala e corredor. Inquilino realojado em alojamento temporário. Processo submetido à Tranquilidade com todos os documentos. Aguarda perito da seguradora.',
      description: 'Na noite de 23 de janeiro de 2026, uma vela decorativa esquecida acesa próximo de um cortinado de tecido leve causou um incêndio que se propagou rapidamente à cozinha de um apartamento do terceiro piso no Porto. O fogo destruiu o cortinado, os móveis de cozinha e afectou a sala de jantar adjacente. Danos por fumo em todo o apartamento. Proprietário e inquilino alertados pelos vizinhos às 23h30; bombeiros chegaram às 23h47.',
    },
    // 15 — Auto / submitted — Allianz
    {
      claim_number: 'CLM-2026-0015',
      insurer_id: allianzId,
      claimant_name: 'Transportes Raposos & Irmão, Lda.',
      claimant_email: 'frota@transportesraposos.pt',
      claimant_phone: '+351 21 888 4400',
      property_address: 'Rua Industrial, 88, 2580-555 Alenquer',
      property_type: 'commercial',
      claim_type: 'auto',
      status: 'submitted',
      date_opened: '2026-02-04',
      date_closed: null,
      estimated_value: 43000,
      final_settlement: null,
      adjuster_notes: 'Colisão de veículo pesado de mercadorias na A1 com guarda-corpos metálico, causando danos na frente, travessia dianteira e suspensão. Condutor ileso mas veículo imobilizado na via. Relatório da PSP e relatório técnico da oficina de camiões obtidos. Processo submetido à Allianz com avaliação de dano total. Aguarda decisão da seguradora sobre reparação vs. perda total.',
      description: 'Em 2 de fevereiro de 2026, às 05h30, um camião pesado de mercadorias (Mercedes Actros, matrícula II-55-JJ) da frota da empresa perdeu o controlo na saída 6 da A1 devido a piso gelado e embateu contra o guarda-corpos metálico. A frente do veículo ficou destruída. Pneus dianteiros rebentados, travessia partida e chassis deformado. Condutor saiu ileso. Carga (material de construção) parcialmente danificada.',
    },
    // 16 — Danos Materiais / new — Fidelidade
    {
      claim_number: 'CLM-2026-0016',
      insurer_id: fidelidadeId,
      claimant_name: 'Isabel Fonseca Neves',
      claimant_email: 'isabel.neves@gmail.com',
      claimant_phone: '+351 912 456 789',
      property_address: 'Rua da Esperança, 67, 1200-654 Lisboa',
      property_type: 'residential',
      claim_type: 'property_damage',
      status: 'new',
      date_opened: '2026-03-05',
      date_closed: null,
      estimated_value: 7200,
      final_settlement: null,
      adjuster_notes: '',
      description: 'Forte temporal de 3 de março de 2026 com vento de mais de 80 km/h provocou a queda de chumaceira e de parte do friso decorativo da fachada do edifício sobre o pátio. Danos no pátio de terraço: calçada portuguesa partida em área de 12 m², tubagem de rega danificada e vidro da estufa de jardim partido. Também reportada a abertura de fissuras na parede de alvenaria junto à janela da cozinha.',
    },
    // 17 — Furto / new — Tranquilidade
    {
      claim_number: 'CLM-2026-0017',
      insurer_id: tranquilidadeId,
      claimant_name: 'Farmácia Central de Coimbra, Lda.',
      claimant_email: 'farmacia@centralcoimbra.pt',
      claimant_phone: '+351 239 445 566',
      property_address: 'Rua da Sofia, 58, 3000-392 Coimbra',
      property_type: 'commercial',
      claim_type: 'theft',
      status: 'new',
      date_opened: '2026-03-17',
      date_closed: null,
      estimated_value: 23000,
      final_settlement: null,
      adjuster_notes: '',
      description: 'Na noite de 15 de março de 2026, arrombamento da porta principal da farmácia com recurso a grampo hidráulico. Foram furtados medicamentos de prescrição controlada (psicotrópicos e estupefacientes), produtos de dermofarmácia de alto valor e €1.200 do caixa. INFARMED e PSP notificados imediatamente. Lista de medicamentos furtados fornecida ao Ministério da Saúde. Câmeras de vigilância internas gravaram o assalto.',
    },
    // 18 — Outros / new — Allianz
    {
      claim_number: 'CLM-2026-0018',
      insurer_id: allianzId,
      claimant_name: 'Escola Internacional de Lisboa, Lda.',
      claimant_email: 'administracao@eilisboa.pt',
      claimant_phone: '+351 21 720 9900',
      property_address: 'Rua da Escola, 1, 2750-412 Cascais',
      property_type: 'commercial',
      claim_type: 'other',
      status: 'new',
      date_opened: '2026-03-28',
      date_closed: null,
      estimated_value: 34000,
      final_settlement: null,
      adjuster_notes: '',
      description: 'Colapso parcial do tecto de uma sala de aula do segundo andar devido a acumulação de água de uma caleira entupida. O tecto falso de 40 m² desabou durante o intervalo, sem causar feridos. Danos materiais: tecto falso destruído, pavimento de linóleo embebido em água, mesas e cadeiras danificadas e projector de tecto destruído. Sala encerrada até reparação. Restantes salas do segundo andar a ser inspeccionadas preventivamente.',
    },
    // 19 — Inundação / disputed — Fidelidade
    {
      claim_number: 'CLM-2026-0019',
      insurer_id: fidelidadeId,
      claimant_name: 'Empreendimentos Costa Vicentina, S.A.',
      claimant_email: 'sinistros@costavicentina.pt',
      claimant_phone: '+351 282 765 400',
      property_address: 'Herdade do Vale do Corvo, 7630-592 Odemira',
      property_type: 'commercial',
      claim_type: 'flood',
      status: 'disputed',
      date_opened: '2026-01-30',
      date_closed: null,
      estimated_value: 380000,
      final_settlement: null,
      adjuster_notes: 'Sinistro em disputa: a seguradora contesta a cobertura alegando que as inundações resultaram de falha de infraestrutura de drenagem do próprio empreendimento e não de evento meteorológico catastrófico. Empresa alega o contrário, apoiada em relatório meteorológico do IPMA para evento de 25 de janeiro de 2026. Processo em análise jurídica. Advogado da Fidelidade enviou carta de reserva de cobertura. Mediação marcada para maio.',
      description: 'As chuvas intensas de 25 de janeiro de 2026 causaram inundação grave de um empreendimento de turismo rural no Alentejo Litoral. As várias unidades de alojamento e o pavilhão central foram inundados com água e lamas. A empresa alega que a inundação foi causada exclusivamente pelo evento meteorológico excepcional. A seguradora contestou a cobertura, argumentando que o sistema de drenagem do empreendimento não estava em conformidade com o projecto aprovado.',
    },
    // 20 — Danos Materiais / new — Tranquilidade
    {
      claim_number: 'CLM-2026-0020',
      insurer_id: tranquilidadeId,
      claimant_name: 'Rui e Célia Domingues',
      claimant_email: 'rui.domingues@hotmail.pt',
      claimant_phone: '+351 917 345 678',
      property_address: 'Rua das Acácias Brancas, 33, 2890-112 Alcochete',
      property_type: 'residential',
      claim_type: 'property_damage',
      status: 'new',
      date_opened: '2026-04-10',
      date_closed: null,
      estimated_value: 9500,
      final_settlement: null,
      adjuster_notes: '',
      description: 'Em 8 de abril de 2026, chuva forte com granizo e rajadas de vento atingiram a Margem Sul do Tejo, causando danos na cobertura da moradia. Foram arrancadas ou partidas aproximadamente 25% das telhas lusalite da vertente norte. A calha de zinco da fachada principal foi deformada em toda a extensão. O portão automático da garagem ficou empenado e inoperacional. Há evidência de humidade a entrar pelo telhado no teto do quarto de criança.',
    },
  ]

  const claimIds: number[] = []
  const claimNumbers: string[] = []
  for (const claim of claims) {
    const result = insert.run(claim)
    claimIds.push(result.lastInsertRowid as number)
    claimNumbers.push(claim.claim_number)
  }

  return { claimIds, claimNumbers }
}
