terraform {
  required_version = ">= 1.6"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
  }
}

provider "aws" {
  region = var.region
}

# ── SSH key pair (generated by Terraform) ─────────────────────────────────────
resource "tls_private_key" "ec2" {
  algorithm = "ED25519"
}

resource "aws_key_pair" "ec2" {
  key_name   = "coba-poc-ec2"
  public_key = tls_private_key.ec2.public_key_openssh
}

# ── Compute (EC2 + EBS + IAM + SSM) ──────────────────────────────────────────
module "compute" {
  source = "../../modules/compute"

  region            = var.region
  account_id        = var.account_id
  public_subnet_id  = module.networking.public_subnet_id
  ec2_sg_id         = module.networking.ec2_sg_id
  ssh_key_name      = aws_key_pair.ec2.key_name
  files_bucket_name = var.files_bucket_name
  anthropic_api_key = var.anthropic_api_key
}

# ── Networking (VPC + subnet + IGW + SG + EIP) ───────────────────────────────
module "networking" {
  source = "../../modules/networking"

  region          = var.region
  deploy_ssh_cidr = var.deploy_ssh_cidr
  ec2_instance_id = module.compute.instance_id
}

# ── Storage (S3 files + S3 frontend + VPC endpoint) ──────────────────────────
module "storage" {
  source = "../../modules/storage"

  region                      = var.region
  vpc_id                      = module.networking.vpc_id
  public_route_table_id       = module.networking.public_route_table_id
  files_bucket_name           = var.files_bucket_name
  frontend_bucket_name        = var.frontend_bucket_name
  cloudfront_distribution_arn = module.cdn.distribution_arn
}

# ── CDN (CloudFront with default *.cloudfront.net certificate) ────────────────
module "cdn" {
  source = "../../modules/cdn"

  ec2_origin_domain               = module.networking.elastic_ip_dns
  frontend_bucket_regional_domain = module.storage.frontend_bucket_regional_domain
}

# ── GitHub Actions OIDC role ──────────────────────────────────────────────────
module "github_oidc" {
  source = "../../modules/github_oidc"

  github_repo          = var.github_repo
  frontend_bucket_name = var.frontend_bucket_name
}
